# Generated by Django 5.1.3 on 2025-07-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensordataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SensordataModel',
                'verbose_name_plural': 'SensordataModels',
                'db_table': 'SensorData',
            },
        ),
    ]
