# Generated by Django 5.1.3 on 2025-07-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deviceId', models.IntegerField(verbose_name='Device id')),
            ],
            options={
                'verbose_name': 'DeviceModel',
                'verbose_name_plural': 'DeviceModels',
                'db_table': 'device',
            },
        ),
        migrations.AddField(
            model_name='sensordatamodel',
            name='deviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.devicemodel'),
        ),
    ]
