# Generated by Django 5.1.3 on 2025-07-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devicemodel_sensordatamodel_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='deviceId',
            field=models.IntegerField(unique=True, verbose_name='Device id'),
        ),
        migrations.AlterField(
            model_name='sensordatamodel',
            name='deviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.devicemodel', to_field='deviceId'),
        ),
    ]
