# Generated by Django 5.1.3 on 2025-07-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_devicemodel_deviceid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='api.devicemodel', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'VehicleModel',
                'verbose_name_plural': 'VehicleModels',
                'db_table': 'Vehicle',
            },
        ),
    ]
