# Generated by Django 5.1.3 on 2025-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehiclemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Number'),
        ),
    ]
