# Generated by Django 5.1.3 on 2025-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vehiclemodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[('connected', 'Ulangan'), ('disconnected', 'Ulanmagan')], default='disconnected', max_length=20, verbose_name='Holat'),
        ),
    ]
