# Generated by Django 5.1.3 on 2025-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_devicemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[('connected', 'Ulangan'), ('disconnected', 'Ulanmagan'), ('waiting', 'Kutilmoqda')], default='disconnected', max_length=20, verbose_name='Holat'),
        ),
    ]
