# Generated by Django 5.1.3 on 2025-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_devicemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faolmi ?'),
        ),
    ]
